In [322]:
#Necessary imports
import numpy as np
from numpy.linalg import inv
from numpy import linalg as LNG 
import random

In [323]:
#Lets learn Numpy

In [324]:
#3 X 3 matricies 
A = np.matrix('1 2 3; 3 4 5; 6 7 8')
B = np.matrix('20 21 22; 23 24 25; 26 27 28') 

In [325]:
A

matrix([[1, 2, 3],
        [3, 4, 5],
        [6, 7, 8]])

In [326]:
B

matrix([[20, 21, 22],
        [23, 24, 25],
        [26, 27, 28]])

In [327]:
#Matrix multiplication
np.dot(A,B)

matrix([[144, 150, 156],
        [282, 294, 306],
        [489, 510, 531]])

In [328]:
#Element wise multiplication
np.multiply(A, B)

matrix([[ 20,  42,  66],
        [ 69,  96, 125],
        [156, 189, 224]])

In [329]:
#Reshaped to vectors and multiply
A = np.reshape(A, 9)
B = np.reshape(B, 9)

In [330]:
B

matrix([[20, 21, 22, 23, 24, 25, 26, 27, 28]])

In [331]:
#Transpose of A * B * Inverse of A
Acopy = np.matrix('1 2 3; 3 4 5; 6 7 8')
Bcopy = np.matrix('20 21 22; 23 24 25; 26 27 28') 
Atran = np.transpose(Acopy)
Ainv = inv(Acopy)
val = np.dot(Atran, Bcopy)
np.dot(val, Ainv)

matrix([[   144.,  -4384.,   2192.],
        [  1344., -10880.,   1344.],
        [ -5648.,   3104.,  -1552.]])

In [332]:
#Concatenate A and B to make C
C = np.concatenate((A,B))

In [333]:
C

matrix([[ 1,  2,  3,  3,  4,  5,  6,  7,  8],
        [20, 21, 22, 23, 24, 25, 26, 27, 28]])

In [334]:
#Find the l2 norm of C
l2 = LNG.norm(C, axis=0)
l2

array([20.02498439, 21.09502311, 22.20360331, 23.19482701, 24.33105012,
       25.49509757, 26.68332813, 27.89265136, 29.12043956])

In [335]:
#Random Mask I
I = np.random.randint(256, size =(256,256))

In [336]:
I

array([[237, 165,  39, ..., 155,  23, 154],
       [141, 248, 204, ...,  21, 197,  60],
       [ 57,  11, 191, ...,  46,  75, 109],
       ...,
       [232, 200, 194, ...,  42,  61, 247],
       [214, 241, 123, ...,  27, 197,  85],
       [ 86,  81,  67, ..., 212,  17, 193]])

In [337]:
#Randoom mask M
M = np.random.randint(2, size = (256, 256))

In [338]:
M

array([[0, 0, 0, ..., 0, 1, 1],
       [1, 0, 1, ..., 0, 1, 0],
       [1, 1, 0, ..., 1, 0, 1],
       ...,
       [0, 1, 1, ..., 0, 1, 0],
       [0, 0, 1, ..., 0, 0, 1],
       [0, 1, 1, ..., 0, 0, 1]])

In [339]:
#Replaced mask
iFlat = I.flatten()
mFlat = M.flatten()
for i in range(mFlat.size):
    if mFlat[i] == 0:
        mFlat[i] = iFlat[i]

mFlat.reshape(256,256)

array([[237, 165,  39, ..., 155,   1,   1],
       [  1, 248,   1, ...,  21,   1,  60],
       [  1,   1, 191, ...,   1,  75,   1],
       ...,
       [232,   1,   1, ...,  42,   1, 247],
       [214, 241,   1, ...,  27, 197,   1],
       [ 86,   1,   1, ..., 212,  17,   1]])