In [1]:
#Let's Learn Python

In [2]:
#Necessary imports
import numpy as np
from numpy.linalg import inv
from numpy import linalg as LNG 
import random

In [3]:
#If the module is being run in the main program then the name will be set to "__main__". However, if code that is 
#being imported from another module is being run, then the name of that module will be set to the "__name__" variable.
#A module in python can be viewed as a code library or a file that contains a set of functions, classes and variables.

In [4]:
#Matrix compare function
def matrixCompare(A,B):
    if(A.size != B.size):
        raise Exception("Matricies need to be of same size!")
        return
    else:
        Atran = np.transpose(A)
        Ainv = inv(A)
        val = np.dot(Atran, B)
        return np.dot(val, Ainv)  

In [5]:
A = np.random.randint(10, size = (2,2))
B = np.random.randint(10, size = (2,2))
matrixCompare(A, B)

array([[ 36.52631579, -15.57894737],
       [ 10.31578947,  -4.94736842]])

In [6]:
A = np.random.randint(10, size = (3,3))
B = np.random.randint(10, size = (3,3))
matrixCompare(A, B)

array([[-4.34210526, 16.80921053,  3.13815789],
       [ 4.92105263, 16.78289474, -0.25657895],
       [ 2.47368421, 17.80263158,  0.03947368]])

In [18]:
A = np.random.randint(10, size = (3,3))
B = np.random.randint(10, size = (3,3))
matrixCompare(A,B)

array([[13.57303371, -2.12359551,  2.85393258],
       [ 3.33707865,  0.04494382,  0.3258427 ],
       [31.73033708, -7.23595506,  4.53932584]])

In [8]:
#1 or -1 function
def randomNum():
    val = random.randint(1,10)
    if(val % 2 == 0):
        print(-1)
    else:
        print(1)

In [9]:
randomNum()

-1


In [10]:
randomNum()

1


In [11]:
randomNum()

1


In [12]:
# List --> Tuple
values = [1,2,3,4]
tup = tuple(values) 
print(tup)
print(type(tup))

(1, 2, 3, 4)
<class 'tuple'>


In [13]:
# List --> Numpy Array
vals = [1,2,3,4]
numArr = np.asarray(vals)
print(numArr)
print(type(numArr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [14]:
# List --> Dictionary
listVals = ['Bhuvan', 'abel', 'Jacques']
myDict = {}
for i in range(len(listVals)):
    myDict[i] = listVals[i]

myDict

{0: 'Bhuvan', 1: 'abel', 2: 'Jacques'}

In [15]:
#List created [5,7] using list comprehension
randomList = [0] * 10
for i in range(10):
    randomList[i] = random.randint(0,11)

#Holder for index
tempList = [0] * 11
for i in range(11):
    tempList[i] = i
   
updateVal = [0 if (x >= 5 and x <= 7) else 1 for x in tempList]

updateVal

[1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1]

In [16]:
#[a if C else b for i in items]

#List created with even and odd 
randList = [0] * 10
for i in range(10):
    randList[i] = random.randint(0,11)
    
newList = ["Odd" if x != x % 2 else "Even" for x in randList]

newList

['Odd', 'Odd', 'Even', 'Odd', 'Odd', 'Odd', 'Odd', 'Even', 'Odd', 'Odd']

In [17]:
#3D Array
I = np.random.randint(256, size =(256,256))
Is = np.random.randint(256, size = (256, 256, 3))

for row in range(len(Is)):
    for col in range(len(Is[1])):
        Is[row][col][2] = I[row][col]

Is

array([[[105, 194,  66],
        [ 50,   1, 213],
        [ 91, 175, 146],
        ...,
        [232, 209, 212],
        [171,  58,  10],
        [192, 148, 203]],

       [[ 80, 107, 161],
        [ 69, 218,  63],
        [ 94, 211, 163],
        ...,
        [ 49, 116, 199],
        [ 85,  45, 101],
        [116,  67,  96]],

       [[228, 128, 216],
        [ 58, 151,   3],
        [ 89,  53,  90],
        ...,
        [187, 174, 104],
        [175,  74, 163],
        [ 39, 172, 160]],

       ...,

       [[187, 176, 186],
        [232,  58,  65],
        [252,  13, 161],
        ...,
        [122, 180, 121],
        [168, 235, 202],
        [ 54,  76, 196]],

       [[179,  27, 156],
        [250, 222, 217],
        [248, 183, 152],
        ...,
        [254, 149, 127],
        [178, 133, 221],
        [ 74, 237,  35]],

       [[231,  86, 120],
        [ 63, 226,  28],
        [123, 171, 206],
        ...,
        [ 58, 171, 227],
        [ 64, 203,  63],
        [ 93, 195, 139]]